version: "3.4"
# https://hub.docker.com/_/nginx
services:
  nginx:
    image: nginx:1.18-alpine
    container_name: "nginx"
    restart: always
    tty: true
    ports:
      - 8080:80
      # - 443:443
    volumes: 
      # - ./nginx.conf:/etc/nginx/nginx.conf # not work for wsl
      - ./conf.d/:/etc/nginx/conf.d
      - ./data:/data
