version: "3.4"
# https://hub.docker.com/_/mysql
services:
  mysql:
    # Fix WSL initialize: https://github.com/docker-library/mysql/issues/219
    user: "1000:50"
    image: mysql:5.7.31
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      TZ: Asia/Shanghai
    command: 
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true 
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3606:3606
    volumes: 
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      - ./conf:/etc/mysql
