version: "3.4"
# https://hub.docker.com/_/redis
services:
  redis:
    image: redis:4-alpine3.9
    container_name: "redis4"
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ./data:/data
    command: redis-server --appendonly yes #--requirepass "root-password"
